"use server";

import { revalidatePath } from "next/cache";
import { auth } from "@/auth.config";
import { prisma } from "@/lib/prisma";
import { greedyGenerateDraft } from "./greedy";

export async function autoGenerateDraft() {
  const session = await auth();
  if (!session?.user) throw new Error("Unauthorized");

  const role = (session.user as any).role as string | undefined;
  if (!role || (role !== "SUPERSUPERADMIN" && role !== "SUPERADMIN" && role !== "DEPTADMIN")) {
    throw new Error("Forbidden");
  }

  const result = await greedyGenerateDraft({
    semester: "1st",
    academicYear: "2025-2026"
  });

  revalidatePath("/dashboard/timetabling");
  return result;
}

export async function updateScheduleStatus(id: string, status: "DRAFT" | "PENDING") {
  const session = await auth();
  if (!session?.user) throw new Error("Unauthorized");

  await prisma.schedule.update({
    where: { id },
    data: { status }
  });

  revalidatePath("/dashboard/timetabling");
}

