"use server";

import { revalidatePath } from "next/cache";
import { auth } from "@/auth.config";
import { prisma } from "@/lib/prisma";
import { greedyGenerateDraft } from "./greedy";
import { logAudit } from "@/lib/audit";

export async function autoGenerateDraft() {
  const session = await auth();
  if (!session?.user) throw new Error("Unauthorized");

  const role = (session.user as any).role as string | undefined;
  const collegeId = (session.user as any).collegeId as string | undefined;
  if (!role || (role !== "COLLEGE_ADMIN" && role !== "DOI")) {
    throw new Error("Forbidden");
  }
  // College Admin can only generate for their college
  if (role === "COLLEGE_ADMIN" && !collegeId) {
    throw new Error("Forbidden: college assignment required");
  }

  const result = await greedyGenerateDraft({
    semester: "1st",
    academicYear: "2025-2026",
    collegeId: role === "COLLEGE_ADMIN" ? collegeId : undefined
  });

  await logAudit(
    (session.user as any).id,
    "Schedule",
    "AUTO_GENERATE",
    "AUTO_GENERATE",
    `Greedy auto-generate run by ${role}`
  );

  revalidatePath("/dashboard/timetabling");
  return result;
}

export async function updateScheduleStatus(id: string, status: "DRAFT" | "PENDING") {
  const session = await auth();
  if (!session?.user) throw new Error("Unauthorized");

  const role = (session.user as any).role as string | undefined;
  const collegeId = (session.user as any).collegeId as string | undefined;

  if (role === "COLLEGE_ADMIN" && collegeId) {
    const schedule = await prisma.schedule.findUnique({
      where: { id },
      include: { section: { include: { program: true } } }
    });
    if (!schedule || schedule.section.program.collegeId !== collegeId) {
      throw new Error("Forbidden: you can only modify schedules in your college");
    }
  }

  await prisma.schedule.update({
    where: { id },
    data: { status }
  });

  await logAudit(
    (session.user as any).id,
    "Schedule",
    id,
    "STATUS_CHANGE",
    `Status changed to ${status}`
  );

  revalidatePath("/dashboard/timetabling");
}

