import { prisma } from "@/lib/prisma";
import { auth } from "@/auth.config";
import { autoGenerateDraft, updateScheduleStatus } from "./actions";
import { TimetablingClient } from "./timetabling-client";

async function getData() {
  const session = await auth();
  if (!session?.user) {
    throw new Error("Unauthorized");
  }

  const role = (session.user as any).role as string | undefined;
  const collegeId = (session.user as any).collegeId as string | undefined;
  const programId = (session.user as any).programId as string | undefined;
  const userId = (session.user as any).id as string | undefined;

  let where: any = {};

  if (role === "DOI") {
    // campus-wide view
    where = {};
  } else if (role === "COLLEGE_ADMIN") {
    // college-level view
    where = collegeId
      ? {
          section: {
            program: {
              collegeId
            }
          }
        }
      : {};
  } else if (role === "CHAIRMAN_ADMIN") {
    // program-level view
    where = programId
      ? {
          section: {
            programId
          }
        }
      : {};
  } else if (role === "INSTRUCTOR") {
    // instructor sees own load only
    where = userId ? { instructorId: userId } : { id: "__none__" };
  } else {
    // other roles: no direct access
    where = { id: "__none__" };
  }

  const [schedules, rooms] = await Promise.all([
    prisma.schedule.findMany({
      where,
      include: {
        subject: true,
        instructor: true,
        section: { include: { program: true } },
        room: true
      },
      orderBy: [{ day: "asc" }, { startTime: "asc" }]
    }),
    prisma.room.findMany({ orderBy: { code: "asc" } })
  ]);
  return { schedules, rooms };
}

export default async function TimetablingPage() {
  const { schedules, rooms } = await getData();
  const session = await auth();
  const role = (session?.user as any)?.role as string | undefined;
  const canGenerate = role === "COLLEGE_ADMIN" || role === "DOI";
  const canToggle = canGenerate || role === "CHAIRMAN_ADMIN";

  async function onGenerate() {
    "use server";
    await autoGenerateDraft();
  }

  async function onToggleStatus(id: string, current: string) {
    "use server";
    await updateScheduleStatus(id, current === "DRAFT" ? "PENDING" : "DRAFT");
  }

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-4">
      <div>
        <h1 className="text-xl font-semibold tracking-tight text-slate-50">
          Academic Timetabling & Optimization
        </h1>
        <p className="text-xs text-slate-400">
          Build schedules, detect conflicts, and view by room.
        </p>
      </div>
      <TimetablingClient
        schedules={schedules}
        rooms={rooms}
        onGenerate={onGenerate}
        onToggleStatus={onToggleStatus}
        canGenerate={!!canGenerate}
        canToggle={!!canToggle}
      />
    </div>
  );
}

