import { prisma } from "@/lib/prisma";
import { autoGenerateDraft, updateScheduleStatus } from "./actions";
import { Button } from "@/components/ui/button";

function hasConflict(schedule: any, all: any[]): boolean {
  return all.some(
    (other) =>
      other.id !== schedule.id &&
      other.day === schedule.day &&
      other.startTime === schedule.startTime &&
      other.endTime === schedule.endTime &&
      (other.roomId === schedule.roomId ||
        other.instructorId === schedule.instructorId ||
        other.sectionId === schedule.sectionId)
  );
}

async function getData() {
  const schedules = await prisma.schedule.findMany({
    include: {
      subject: true,
      instructor: true,
      section: { include: { major: true } },
      room: true
    },
    orderBy: [{ day: "asc" }, { startTime: "asc" }]
  });
  return schedules;
}

export default async function TimetablingPage() {
  const schedules = await getData();

  async function onGenerate() {
    "use server";
    await autoGenerateDraft();
  }

  async function onToggleStatus(id: string, current: string) {
    "use server";
    await updateScheduleStatus(id, current === "DRAFT" ? "PENDING" : "DRAFT");
  }

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold tracking-tight text-slate-50">
            Academic Timetabling & Optimization
          </h1>
          <p className="text-xs text-slate-400">
            Predefined time slots, greedy auto-generate, and conflict highlighting.
          </p>
        </div>
        <form action={onGenerate}>
          <Button type="submit" size="sm">
            Auto Generate Draft
          </Button>
        </form>
      </div>
      <div className="glass-panel overflow-hidden rounded-2xl">
        <div className="max-h-[460px] overflow-auto text-xs">
          <table className="w-full border-collapse text-left">
            <thead className="bg-slate-900/80 text-[11px] uppercase tracking-[0.14em] text-slate-400">
              <tr>
                <th className="px-3 py-2">Day</th>
                <th className="px-3 py-2">Time</th>
                <th className="px-3 py-2">Subject</th>
                <th className="px-3 py-2">Section</th>
                <th className="px-3 py-2">Instructor</th>
                <th className="px-3 py-2">Room</th>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {schedules.map((s) => {
                const conflict = hasConflict(s, schedules);
                return (
                  <tr
                    key={s.id}
                    className={conflict ? "bg-red-950/50" : "odd:bg-slate-900/40"}
                  >
                    <td className="px-3 py-2">{s.day}</td>
                    <td className="px-3 py-2">
                      {s.startTime}–{s.endTime}
                    </td>
                    <td className="px-3 py-2">
                      <span className="font-medium text-slate-100">{s.subject.code}</span>{" "}
                      <span className="text-slate-400">· {s.subject.title}</span>
                    </td>
                    <td className="px-3 py-2">
                      {s.section.major.code} {s.section.name}
                    </td>
                    <td className="px-3 py-2">{s.instructor.name}</td>
                    <td className="px-3 py-2">{s.room.code}</td>
                    <td className="px-3 py-2">
                      <span
                        className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-semibold ${
                          s.status === "DRAFT"
                            ? "bg-slate-800 text-slate-200"
                            : "bg-amber-500/20 text-amber-300"
                        }`}
                      >
                        {s.status}
                      </span>
                    </td>
                    <td className="px-3 py-2 text-right">
                      <form
                        action={async () => {
                          "use server";
                          await updateScheduleStatus(
                            s.id,
                            s.status === "DRAFT" ? "PENDING" : "DRAFT"
                          );
                        }}
                      >
                        <Button
                          type="submit"
                          variant="ghost"
                          size="sm"
                          className="text-[11px]"
                        >
                          {s.status === "DRAFT" ? "Mark Pending" : "Mark Draft"}
                        </Button>
                      </form>
                    </td>
                  </tr>
                );
              })}
              {schedules.length === 0 && (
                <tr>
                  <td
                    colSpan={8}
                    className="px-3 py-10 text-center text-xs text-slate-400"
                  >
                    No schedules yet. Use{" "}
                    <span className="font-semibold text-brand-teal">
                      Auto Generate Draft
                    </span>{" "}
                    to create a baseline timetable, then refine manually.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

