import { prisma } from "@/lib/prisma";
import { auth } from "@/auth.config";
import { autoGenerateDraft, updateScheduleStatus } from "./actions";
import { TimetablingClient } from "./timetabling-client";
import { Button } from "@/components/ui/button";

async function getData() {
  const session = await auth();
  if (!session?.user) {
    throw new Error("Unauthorized");
  }

  const role = (session.user as any).role as string | undefined;
  const collegeId = (session.user as any).collegeId as string | undefined;
  const programId = (session.user as any).programId as string | undefined;
  const userId = (session.user as any).id as string | undefined;

  let where: any = {};

  if (role === "DOI") {
    // campus-wide view
    where = {};
  } else if (role === "COLLEGE_ADMIN") {
    // college-level view
    where = collegeId
      ? {
          section: {
            program: {
              collegeId
            }
          }
        }
      : {};
  } else if (role === "CHAIRMAN_ADMIN") {
    // program-level view
    where = programId
      ? {
          section: {
            programId
          }
        }
      : {};
  } else if (role === "INSTRUCTOR") {
    // instructor sees own load only
    where = userId ? { instructorId: userId } : { id: "__none__" };
  } else {
    // other roles: no direct access
    where = { id: "__none__" };
  }

  const schedules = await prisma.schedule.findMany({
    where,
    include: {
      subject: true,
      instructor: true,
      section: { include: { program: true } },
      room: true
    },
    orderBy: [{ day: "asc" }, { startTime: "asc" }]
  });

  // Rooms are scoped by role:
  // - DOI / College Admin: see all rooms
  // - Chairman Admin: only rooms actually used by their program’s schedules
  // - Instructors / others: no direct timetabling actions
  let roomWhere: any = {};
  if (role === "CHAIRMAN_ADMIN" && programId) {
    const roomIds = Array.from(new Set(schedules.map((s) => s.roomId)));
    roomWhere = roomIds.length > 0 ? { id: { in: roomIds } } : { id: "__none__" };
  }

  const rooms = await prisma.room.findMany({
    where: roomWhere,
    orderBy: { code: "asc" }
  });

  // Data for schedule creation form (used by Chairman / College Admin)
  let subjects: any[] = [];
  let sections: any[] = [];
  let instructors: any[] = [];

  if (role === "COLLEGE_ADMIN" && collegeId) {
    [subjects, sections, instructors] = await Promise.all([
      prisma.subject.findMany({ orderBy: { code: "asc" } }),
      prisma.section.findMany({
        where: { program: { collegeId } },
        include: { program: true },
        orderBy: { name: "asc" }
      }),
      prisma.user.findMany({
        where: { role: "INSTRUCTOR", collegeId },
        orderBy: { name: "asc" }
      })
    ]);
  } else if (role === "CHAIRMAN_ADMIN" && programId) {
    [subjects, sections, instructors] = await Promise.all([
      prisma.subject.findMany({ orderBy: { code: "asc" } }),
      prisma.section.findMany({
        where: { programId },
        include: { program: true },
        orderBy: { name: "asc" }
      }),
      prisma.user.findMany({
        where: { role: "INSTRUCTOR", programId },
        orderBy: { name: "asc" }
      })
    ]);
  }

  return { schedules, rooms, subjects, sections, instructors };
}

export default async function TimetablingPage() {
  const { schedules, rooms, subjects, sections, instructors } = await getData();
  const session = await auth();
  const role = (session?.user as any)?.role as string | undefined;
  const canGenerate = role === "COLLEGE_ADMIN" || role === "DOI";
  const canToggle = canGenerate || role === "CHAIRMAN_ADMIN";
  const isChairOrCollege = role === "CHAIRMAN_ADMIN" || role === "COLLEGE_ADMIN";

  async function createSchedule(formData: FormData) {
    "use server";
    const s = await auth();
    if (!s?.user) throw new Error("Unauthorized");
    const r = (s.user as any).role as string | undefined;
    const collegeId = (s.user as any).collegeId as string | undefined;
    const programId = (s.user as any).programId as string | undefined;

    if (r !== "COLLEGE_ADMIN" && r !== "CHAIRMAN_ADMIN") {
      throw new Error("Forbidden");
    }

    const subjectId = formData.get("subjectId")?.toString() ?? "";
    const sectionId = formData.get("sectionId")?.toString() ?? "";
    const instructorId = formData.get("instructorId")?.toString() ?? "";
    const roomId = formData.get("roomId")?.toString() ?? "";
    const day = formData.get("day")?.toString() ?? "";
    const startTime = formData.get("startTime")?.toString() ?? "";
    const endTime = formData.get("endTime")?.toString() ?? "";

    if (!subjectId || !sectionId || !instructorId || !roomId || !day || !startTime || !endTime) {
      throw new Error("Missing fields");
    }

    // Scope enforcement: Chairman can only schedule within their program.
    if (r === "CHAIRMAN_ADMIN" && programId) {
      const section = await prisma.section.findUnique({
        where: { id: sectionId },
        select: { programId: true }
      });
      if (!section || section.programId !== programId) {
        throw new Error("Forbidden: section not in your program");
      }
    }

    if (r === "COLLEGE_ADMIN" && collegeId) {
      const section = await prisma.section.findUnique({
        where: { id: sectionId },
        select: { program: { select: { collegeId: true } } }
      });
      if (!section || section.program.collegeId !== collegeId) {
        throw new Error("Forbidden: section not in your college");
      }
    }

    await prisma.schedule.create({
      data: {
        subjectId,
        instructorId,
        sectionId,
        roomId,
        day: day as any,
        startTime,
        endTime,
        status: "DRAFT",
        semester: "1st",
        academicYear: "2025-2026"
      }
    });
  }

  async function onGenerate() {
    "use server";
    await autoGenerateDraft();
  }

  async function onToggleStatus(id: string, current: string) {
    "use server";
    await updateScheduleStatus(id, current === "DRAFT" ? "PENDING" : "DRAFT");
  }

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-4">
      <div>
        <h1 className="text-xl font-semibold tracking-tight text-slate-50">
          Academic Timetabling & Optimization
        </h1>
        <p className="text-xs text-slate-400">
          Build schedules, detect conflicts, and view by room.
        </p>
      </div>
      {isChairOrCollege && (
        <div className="glass-panel rounded-2xl px-4 py-3 text-xs text-slate-200">
          <p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">
            Create Schedule (Draft)
          </p>
          <form action={createSchedule} className="grid gap-2 md:grid-cols-6">
            <select
              name="subjectId"
              className="h-8 rounded-md border border-slate-700 bg-slate-900 px-2 text-[11px] text-slate-100"
              required
            >
              <option value="">Subject</option>
              {subjects.map((s: any) => (
                <option key={s.id} value={s.id}>
                  {s.code}
                </option>
              ))}
            </select>
            <select
              name="sectionId"
              className="h-8 rounded-md border border-slate-700 bg-slate-900 px-2 text-[11px] text-slate-100"
              required
            >
              <option value="">Section</option>
              {sections.map((sec: any) => (
                <option key={sec.id} value={sec.id}>
                  {sec.program.code} {sec.name}
                </option>
              ))}
            </select>
            <select
              name="instructorId"
              className="h-8 rounded-md border border-slate-700 bg-slate-900 px-2 text-[11px] text-slate-100"
              required
            >
              <option value="">Instructor</option>
              {instructors.map((i: any) => (
                <option key={i.id} value={i.id}>
                  {i.name ?? i.email}
                </option>
              ))}
            </select>
            <select
              name="roomId"
              className="h-8 rounded-md border border-slate-700 bg-slate-900 px-2 text-[11px] text-slate-100"
              required
            >
              <option value="">Room</option>
              {rooms.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.code}
                </option>
              ))}
            </select>
            <select
              name="day"
              className="h-8 rounded-md border border-slate-700 bg-slate-900 px-2 text-[11px] text-slate-100"
              required
            >
              <option value="">Day</option>
              <option value="MONDAY">Mon</option>
              <option value="TUESDAY">Tue</option>
              <option value="WEDNESDAY">Wed</option>
              <option value="THURSDAY">Thu</option>
              <option value="FRIDAY">Fri</option>
              <option value="SATURDAY">Sat</option>
            </select>
            <div className="flex gap-1">
              <input
                name="startTime"
                type="time"
                className="h-8 flex-1 rounded-md border border-slate-700 bg-slate-900 px-2 text-[11px] text-slate-100"
                required
              />
              <input
                name="endTime"
                type="time"
                className="h-8 flex-1 rounded-md border border-slate-700 bg-slate-900 px-2 text-[11px] text-slate-100"
                required
              />
            </div>
            <div className="md:col-span-6 flex justify-end pt-1">
              <Button type="submit" size="sm">
                Add to Draft
              </Button>
            </div>
          </form>
        </div>
      )}
      <TimetablingClient
        schedules={schedules}
        rooms={rooms}
        onGenerate={onGenerate}
        onToggleStatus={onToggleStatus}
        canGenerate={!!canGenerate}
        canToggle={!!canToggle}
      />
    </div>
  );
}

